
GET  https://api.binance.com/api/v3/ticker/24hr?symbol=BTCEUR HTTP/1.0

###


GET  https://api.binance.com/api/v3/avgPrice?symbol=BTCEUR HTTP/1.0

###

GET  https://api.binance.com/api/v3/ticker/price?symbol=BTCEUR HTTP/1.0

###

GET  https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1h&limit=24 HTTP/1.0

###


GET https://api.binance.com/api/v3/klines?symbol=BTCEUR&interval=1m&limit=50


###

Web Socket Stream

wss://stream.binance.com:9443/ws/btceur@miniTicker

###



