GET https://api.coingecko.com/api/v3/ping HTTP/1.0

###

GET https://api.coingecko.com/api/v3/coins/list?include_platform=false HTTP/1.0


###


GET https://api.coingecko.com/api/v3/simple/supported_vs_currencies


###

GET https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=eur,usd&include_24hr_change=true HTTP/1.0

###


GET https://api.coingecko.com/api/v3/coins/bitcoin?localization=false&tickers=false&market_data=false&community_data=false&developer_data=false&sparkline=false HTTP/1.0


###


GET https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=eur&days=2 HTTP/1.0

###


GET https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=eur&days=365 HTTP/1.0

###


GET https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=eur&days=90&interval=daily HTTP/1.0


###

GET https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100

###

GET https://api.coingecko.com/api/v3/coins/ethereum?localization=false&tickers=false&market_data=false&community_data=false&developer_data=false&sparkline=false

###


###



